[project]
template = "docx/template.docx"
header = "docx/header.docx"
output = "output.docx"
pictures = "pictures"

[input]
files = [
    "markdown/abstract.md",
    "markdown/table_of_contents.md",
    "markdown/definitions.md",
    "markdown/intro.md",
    "markdown/1.md",
    "markdown/conclusion.md",
    "markdown/references.md",
    "markdown/appendix_a.md",
]
bibliography = "markdown/reference.bib"

[render]
title_pages = ["РЕФЕРАТ", "ABSTRACT", "СОДЕРЖАНИЕ"]
centered_headings = [
    "ОПРЕДЕЛЕНИЯ, ОБОЗНАЧЕНИЯ И СОКРАЩЕНИЯ (заголовок второго уровня)",
    "ВВЕДЕНИЕ (заголовок второго уровня)",
    "ЗАКЛЮЧЕНИЕ (заголовок второго уровня)",
    "СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ",
]

[stats]
manual_pages = 10
